services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    ports:
     - 8123:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dist:/config/www
      - ./ha-dev-config/configuration.yaml:/config/configuration.yaml
      - ./ha-dev-config/dashboard.yaml:/config/dashboard.yaml
